version: "3.5"
services:
  crawler:
    image: ghcr.io/tonywangcn/distributed-web-crawler:go-crawler-latest
    container_name: crawler
    restart: always
    env_file:
      - .env
    command: [ "/main"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    image: ghcr.io/tonywangcn/distributed-web-crawler:go-crawler-latest
    container_name: worker
    restart: always
    env_file:
      - .env
    command: [ "/main", "-w", "worker", "-c", "2" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  node:
    image: apify/actor-node-puppeteer-chrome:latest
    container_name: node
    env_file:
      - .env
    volumes:
      - "./node/:/code/"
    working_dir: /code/
    restart: always
    command: [ "tail", "-f", "/dev/null" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
